export type HeritageDetail = {
  _id: string
  markerId: number
  title: string
  category: string
  summary: string
  story: string
  images: string[]
  inheritorName: string
  inheritorBio: string
  inheritorPhoto: string
  relatedMarkerIds: number[]
  status: string
  videoUrl: string
  videoCover: string
}

export type HeritageListItem = {
  _id: string
  markerId: number
  title: string
  category: string
  summary: string
  images: string[]
}
