// Minimal Pinia-compatible defineStore shim for uniapp x
// Replaces `import { defineStore } from 'pinia'` with this local implementation

type StoreSetup = () => any

export function defineStore(_id: string, setup: StoreSetup): () => any {
  let inited: boolean = false
  let instance: any = null
  return (): any => {
    if (inited) return instance
    inited = true
    instance = setup()
    return instance
  }
}
